#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 1

#define ERROR_ALLOC_POINT 5
#define ERROR_ALLOC_MODEL 7
#define ERROR_ALLOC_MODEL_PROJ 8
#define ERROR_ALLOC_POINTS_ARRAY 14
#define ERROR_ALLOC_POINTS_PROJ_ARRAY 15
#define ERROR_ALLOC_LINKS_MATRIX 16
#define ERROR_ALLOC_MATRIX 20

#define ERROR_OPER_TYPE 100

#define ERROR_LOAD_MODEL 150


#define ERROR_FILE_OPEN 16
#define ERROR_FILE_DATA 17

#endif // ERRORS_H
